name: Run Kotlin Code on Main

# Trigger the workflow on push to the main branch
on: workflow_dispatch

jobs:
  run-kotlin:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    # Install Kotlin
    - name: Install Kotlin
      run: sudo apt-get update && sudo apt-get install -y default-jdk && curl -s https://get.sdkman.io | bash && source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install kotlin

    # Compile and run the Kotlin script
    - name: Run Kotlin Script
      run: kotlinc "All Code that there is.kt" -include-runtime -d main.jar && java -jar main.jar
